// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cmonbart
RcppExport SEXP cmonbart(SEXP ix, SEXP iy, SEXP ixp, SEXP itau, SEXP inu, SEXP ilambda, SEXP ibase, SEXP ipower, SEXP ioffset, SEXP ind, SEXP iburn, SEXP im, SEXP imgsize, SEXP inkeeptrain, SEXP inkeeptest, SEXP inkeeptreedraws, SEXP inprintevery);
RcppExport SEXP _pmBART_cmonbart(SEXP ixSEXP, SEXP iySEXP, SEXP ixpSEXP, SEXP itauSEXP, SEXP inuSEXP, SEXP ilambdaSEXP, SEXP ibaseSEXP, SEXP ipowerSEXP, SEXP ioffsetSEXP, SEXP indSEXP, SEXP iburnSEXP, SEXP imSEXP, SEXP imgsizeSEXP, SEXP inkeeptrainSEXP, SEXP inkeeptestSEXP, SEXP inkeeptreedrawsSEXP, SEXP inprinteverySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type ix(ixSEXP);
    Rcpp::traits::input_parameter< SEXP >::type iy(iySEXP);
    Rcpp::traits::input_parameter< SEXP >::type ixp(ixpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type itau(itauSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inu(inuSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ibase(ibaseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ipower(ipowerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ioffset(ioffsetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ind(indSEXP);
    Rcpp::traits::input_parameter< SEXP >::type iburn(iburnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type im(imSEXP);
    Rcpp::traits::input_parameter< SEXP >::type imgsize(imgsizeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptrain(inkeeptrainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptest(inkeeptestSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inkeeptreedraws(inkeeptreedrawsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inprintevery(inprinteverySEXP);
    rcpp_result_gen = Rcpp::wrap(cmonbart(ix, iy, ixp, itau, inu, ilambda, ibase, ipower, ioffset, ind, iburn, im, imgsize, inkeeptrain, inkeeptest, inkeeptreedraws, inprintevery));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pmBART_cmonbart", (DL_FUNC) &_pmBART_cmonbart, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_pmBART(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
