# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmonbart <- function(ix, iy, ixp, itau, inu, ilambda, ibase, ipower, ioffset, ind, iburn, im, imgsize, inkeeptrain, inkeeptest, inkeeptestme, inkeeptreedraws, inprintevery) {
    .Call(`_pmBART_cmonbart`, ix, iy, ixp, itau, inu, ilambda, ibase, ipower, ioffset, ind, iburn, im, imgsize, inkeeptrain, inkeeptest, inkeeptestme, inkeeptreedraws, inprintevery)
}

